import type { Metadata } from "next";
import "@/styles/reset.css";
import "@/styles/globals.css";
import "@/styles/font.css";

import Header from '@/components/main/Header';

export const metadata: Metadata = {
    title: "Who Is Me?",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body>
                <Header/>
                {children}
            </body>
        </html>
    );
}
